# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\johan\Desktop\PyQt5\PyQt5\code\1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 230, 112, 34))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sakura")) # 改变窗口名
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
if __name__ == '__main__':
  app = QtWidgets.QApplication(sys.argv)
  MainWindow = QtWidgets.QMainWindow()
  ui = Ui_MainWindow()
  ui.setupUi(MainWindow)
  screen = QDesktopWidget().screenGeometry() ## 获取宽和高 
  width = screen.width()
  height = screen.height()
  #print(width, height)
  icon = QtGui.QIcon()
  icon.addPixmap(QtGui.QPixmap('PyQt5\code\w1.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
  MainWindow.setStyleSheet('#MainWindow{background-color:red
        background}')
  MainWindow.setWindowIcon(icon)
  MainWindow.show()
  sys.exit(app.exec_())